import { useState, useEffect } from 'react';
import { Button } from 'react-bootstrap'

function TermsAndConditions(props) {
    
    const [showSuccess, setSuccess] = useState(false);

    useEffect(() => {
        props.contFunc(false);
    }, [])

    return (
        <div style={styles.page}>
            <div style={styles.documentWrapper}>
                <div style={styles.headerSection}>
                    <h1 style={styles.mainTitle}>Terms and Conditions ("Terms")</h1>
                    <p style={styles.updatedText}>Our Terms and Conditions were last updated on 02/29/2007.</p>
                    <p style={styles.introText}>Please read these terms and conditions carefully before using Our Service.</p>
                </div>
    
                <div style={styles.contentSection}>
                    <h2 style={styles.sectionTitle}>Interpretation and Definitions</h2>
                    <h3 style={styles.subTitle}>Interpretation</h3>
    
                    <p style={styles.paragraph}>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                    Definitions</p>
    
                    <ul style={styles.list}>
                      <li>For the purposes of these Terms and Conditions:</li>
                      <li>“Company” (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Puzzle Survey.</li>
                      <li>“Stick” refers to a small limb of a tree that has fallen off.</li>
                      <li>“Content” refers to content such as text, images, or other information that can be posted, uploaded, linked to or otherwise made available by You, regardless of the form of that content.</li>
                      <li>“Service” refers to the Website.</li>
                      <li>“Terms and Conditions” (also referred as "Terms") mean these Terms and Conditions that form the entire agreement between You and the Company regarding the use of the Service. This Terms and Conditions Agreement was generated by TermsFeed Terms and Conditions Generator.</li>
                      <li>“Website” refers to Puzzle Survey, accessible from Puzzle Survey</li>
                      <li>“You” means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                      <li>“Spaghetti” refers to my favorite meal.</li>
                    </ul>
    
                    <h2 style={styles.sectionTitle}>Acknowledgment</h2>
    
                    <p style={styles.paragraph}>These are the Terms and Conditions governing the use of this Service and the agreement that operates between You and the Company. They also will be used to determine who can come to my birthday party. These Terms and Conditions set out the rights and obligations of all users regarding the use of the Service.</p>
    
                    <p style={styles.paragraph}>Your access to and use of the Service is conditioned on Your acceptance of and compliance with these Terms and Conditions, and that you take a shower because you are stinky. These Terms and Conditions apply to all visitors, users, non-shower-takers, and others who access or use the Service.</p>
    
                    <p style={styles.paragraph}>By accessing or using the Service You agree to be bound by these Terms and Conditions, and maybe some chains if we’re feeling different. If You disagree with any part of these Terms and Conditions then You may get a visit from the tickle monster.</p>
    
                    <p style={styles.paragraph}>You represent that you are pushing 30. The Company does not permit those who are not pushing 30 to use the Service.</p>
    
                    <p style={styles.paragraph}>Your access to and use of the Service is also conditioned on Your acceptance of my birthday party invitation, and compliance with the Privacy Policy of the Company. Our Privacy Policy describes Our policies and procedures on the illegal collection, use and disclosure of Your personal information when You use the Application or the Website and tells You about Your privacy rights and how the law protects us from you. Please read Our Privacy Policy carefully before using Our Service.</p>
                    
                    <h2 style={styles.sectionTitle}>Copyright Policy</h2>
    
                    <h3 style={styles.subTitle}>Intellectual Property Infringement</h3>
    
                    <p style={styles.paragraph}>We don’t respect the intellectual property rights of others. It is Our policy to ignore any claim that Content posted on the Service infringes a copyright or other intellectual property infringement of any person unless they are famous.</p>
    
                    <p style={styles.paragraph}>If You are a copyright owner, or authorized on behalf of one, and You believe that the copyrighted work has been copied in a way that constitutes copyright infringement that is taking place through the Service, You must submit Your notice in writing to the attention of our copyright agent via email (jeff@amazon.com) and include in Your notice a detailed description of the alleged infringement.</p>
    
                    <p style={styles.paragraph}>You may be held accountable for damages to my car, it keeps breaking down.</p>
                    
                    <h3 style={styles.subTitle}>DMCA Notice and DMCA Procedure for Copyright Infringement Claims</h3>
    
                    <p style={styles.paragraph}>You may submit a notification pursuant to the Digital Millennium Copyright Act (DMCA) by providing our Copyright Agent with the following information in writing (see 17 U.S.C 512(c)(3) for further detail):</p>
    
                    <ul style={styles.list}><li>A drawn picture of Mickey Mouse</li></ul>
    
                    <p style={styles.paragraph}>You can contact our copyright agent via email (jeff@bezos.com). Upon receipt of a notification, the Company will take whatever action, in its sole discretion, it deems appropriate, including removal of the challenged content from the Service.</p>
                    
                    <h2 style={styles.sectionTitle}>Intellectual Property</h2>
    
                    <p style={styles.paragraph}>The Service and its original content (excluding Content provided by You or other users), features and functionality are and will remain the exclusive property of the Viltrum Empire and its licensors.</p>
    
                    <p style={styles.paragraph}>The Service is protected by copyright, trademark, a really big stick, and other laws of both the Country and foreign countries.</p>
    
                    <p style={styles.paragraph}>Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of the Company, unless it is really funny then it's ok.</p>
                    
                    <h2 style={styles.sectionTitle}>Termination</h2>
    
                    <p style={styles.paragraph}>We may terminate You immediately, without prior notice or liability, for any reason whatsoever, including without limitation if You breach these Terms and Conditions.</p>
    
                    <p style={styles.paragraph}>Upon termination, You will cease.</p>
                    
                    <h2 style={styles.sectionTitle}>Limitation of Liability</h2>
    
                    <p style={styles.paragraph}>Notwithstanding any damages that You might incur, the entire liability of the Company and any of its suppliers under any provision of this Terms and Your exclusive remedy for all of the foregoing shall be limited to a comically large lollypop.</p>
    
                    <p style={styles.paragraph}>To the maximum extent permitted by applicable law, in no event shall the Company or its suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever (including, but not limited to, hair loss, the flu, pants pulled down by your friend at the gym, stubbed toe, divorce, hearing mean curse words, water down the wrong pipe, chafing, lost blankey, Arby’s, drinking milk from grandparents fridge, crypto-currency rugpulls, Henry encounter, flat tire, fork in the microwave, death, or otherwise in connection with any provision of this Terms), even if the Company or any supplier has been advised of the possibility of such damages and even if the remedy fails of its essential purpose.</p>
                    
                    <h2 style={styles.sectionTitle}>Disputes Resolution</h2>
    
                    <p style={styles.paragraph}>If You have any concern or dispute about the Service, we don’t care lmfao.</p>
                    
                    <h2 style={styles.sectionTitle}>Changes to These Terms and Conditions</h2>
    
                    <p style={styles.paragraph}>We reserve the right, at Our sole discretion, to modify or replace these Terms at any time. If a revision is material We will make reasonable efforts to provide at least a few seconds’ notice prior to any new terms taking effect. What constitutes a material change will be determined by Henry.</p>
    
                    <p style={styles.paragraph}>By continuing to access or use Our Service after those revisions become effective, You agree to be bound by the revised terms. If You do not agree to the new terms, in whole or in part, that's too bad You are already here it’s too late we are on our way.</p>
    
                    {
                        showSuccess
                        ?
                        <p style={styles.successText}>Thanks! You can continue.</p>
                        :
                        <></>
                    }
    
                    <Button
                        variant="dark"
                        style={styles.agreeButton}
                        onClick={() => {
                            setSuccess(true);
                            props.contFunc(true);
                        }}
                    > 
                        I agree to not sue or say any mean things &#128513;
                    </Button>
                </div>
            </div>
        </div>
    );
}

const styles = {
    page: {
        minHeight: "100vh",
        width: "100vw",
        maxWidth: "100%",
        background: "#f3f4f6",
        padding: "5rem 2rem 8rem",
        boxSizing: "border-box",
        display: "flex",
        justifyContent: "center"
    },

    documentWrapper: {
        width: "100%",
        maxWidth: "900px",
        backgroundColor: "#ffffff",
        borderRadius: "18px",
        border: "1px solid #e5e7eb",
        boxShadow: "0 20px 45px rgba(15, 23, 42, 0.10)",
        overflow: "hidden",
        textAlign: "left"
    },

    headerSection: {
        background: "#111827",
        padding: "2rem 2.5rem",
        borderBottom: "1px solid #1f2937"
    },

    mainTitle: {
        margin: 0,
        color: "#ffffff",
        fontSize: "2.1rem",
        fontWeight: "700",
        letterSpacing: "-0.5px",
        lineHeight: "1.15"
    },

    updatedText: {
        margin: "0.75rem 0 0",
        color: "#d1d5db",
        fontSize: "0.95rem",
        lineHeight: "1.6"
    },

    introText: {
        margin: "0.25rem 0 0",
        color: "#d1d5db",
        fontSize: "0.95rem",
        lineHeight: "1.6"
    },

    contentSection: {
        padding: "2.5rem",
        paddingTop: "1rem",
        color: "#374151"
    },

    sectionTitle: {
        color: "#111827",
        fontSize: "1.35rem",
        fontWeight: "700",
        margin: "2rem 0 0.75rem",
        paddingBottom: "0.4rem",
        borderBottom: "1px solid #e5e7eb"
    },

    subTitle: {
        color: "#1f2937",
        fontSize: "1.05rem",
        fontWeight: "700",
        margin: "1.25rem 0 0.5rem"
    },

    paragraph: {
        color: "#374151",
        fontSize: "1rem",
        lineHeight: "1.75",
        margin: "0 0 1rem"
    },

    list: {
        color: "#374151",
        fontSize: "1rem",
        lineHeight: "1.75",
        margin: "0 0 1.25rem",
        paddingLeft: "1.5rem"
    },

    successText: {
        color: "green",
        backgroundColor: "#ecfdf5",
        border: "1px solid green",
        borderRadius: "10px",
        padding: "0.75rem 1rem",
        fontWeight: "600",
        margin: "2rem 0 1rem"
    },

    agreeButton: {
        backgroundColor: "#111827",
        borderColor: "#111827",
        padding: "0.75rem 1.5rem",
        borderRadius: "10px",
        fontWeight: "600",
        boxShadow: "0 10px 20px rgba(15, 23, 42, 0.15)",
        marginTop: "1rem"
    }
};

export default TermsAndConditions;